// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifdsytpdqbftbxghrnrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZHN5dHBkcWJmdGJ4Z2hybnJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDYyNzAsImV4cCI6MjA2MTU4MjI3MH0.PmZKbNGBhTdjiMY6xNTXf09YAkloix4v2oqdyzFv7M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);